# generated by datamodel-codegen:
#   filename:  jikan-openapi.json
#   timestamp: 2026-01-14T06:33:28+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Any

from pydantic import BaseModel, Field


class UserAnimeListStatusFilter(StrEnum):
    all = 'all'
    watching = 'watching'
    completed = 'completed'
    onhold = 'onhold'
    dropped = 'dropped'
    plantowatch = 'plantowatch'


class AnimeSearchQueryOrderby(StrEnum):
    mal_id = 'mal_id'
    title_ = 'title'
    start_date = 'start_date'
    end_date = 'end_date'
    episodes = 'episodes'
    score = 'score'
    scored_by = 'scored_by'
    rank = 'rank'
    popularity = 'popularity'
    members = 'members'
    favorites = 'favorites'


class AnimeSearchQueryRating(StrEnum):
    g = 'g'
    pg = 'pg'
    pg13 = 'pg13'
    r17 = 'r17'
    r = 'r'
    rx = 'rx'


class AnimeSearchQueryStatus(StrEnum):
    airing = 'airing'
    complete = 'complete'
    upcoming = 'upcoming'


class AnimeSearchQueryType(StrEnum):
    tv = 'tv'
    movie = 'movie'
    ova = 'ova'
    special = 'special'
    ona = 'ona'
    music = 'music'
    cm = 'cm'
    pv = 'pv'
    tv_special = 'tv_special'


class CharactersSearchQueryOrderby(StrEnum):
    mal_id = 'mal_id'
    name = 'name'
    favorites = 'favorites'


class ClubSearchQueryCategory(StrEnum):
    anime = 'anime'
    manga = 'manga'
    actors_and_artists = 'actors_and_artists'
    characters = 'characters'
    cities_and_neighborhoods = 'cities_and_neighborhoods'
    companies = 'companies'
    conventions = 'conventions'
    games = 'games'
    japan = 'japan'
    music = 'music'
    other = 'other'
    schools = 'schools'


class ClubSearchQueryOrderby(StrEnum):
    mal_id = 'mal_id'
    name = 'name'
    members_count = 'members_count'
    created = 'created'


class ClubSearchQueryType(StrEnum):
    public = 'public'
    private = 'private'
    secret = 'secret'


class UsersSearchQueryGender(StrEnum):
    any = 'any'
    male = 'male'
    female = 'female'
    nonbinary = 'nonbinary'


class GenreQueryFilter(StrEnum):
    genres = 'genres'
    explicit_genres = 'explicit_genres'
    themes = 'themes'
    demographics = 'demographics'


class MagazinesQueryOrderby(StrEnum):
    mal_id = 'mal_id'
    name = 'name'
    count_ = 'count'


class UserMangaListStatusFilter(StrEnum):
    all = 'all'
    reading = 'reading'
    completed = 'completed'
    onhold = 'onhold'
    dropped = 'dropped'
    plantoread = 'plantoread'


class MangaSearchQueryOrderby(StrEnum):
    mal_id = 'mal_id'
    title_ = 'title'
    start_date = 'start_date'
    end_date = 'end_date'
    chapters = 'chapters'
    volumes = 'volumes'
    score = 'score'
    scored_by = 'scored_by'
    rank = 'rank'
    popularity = 'popularity'
    members = 'members'
    favorites = 'favorites'


class MangaSearchQueryStatus(StrEnum):
    publishing = 'publishing'
    complete = 'complete'
    hiatus = 'hiatus'
    discontinued = 'discontinued'
    upcoming = 'upcoming'


class MangaSearchQueryType(StrEnum):
    manga = 'manga'
    novel = 'novel'
    lightnovel = 'lightnovel'
    oneshot = 'oneshot'
    doujin = 'doujin'
    manhwa = 'manhwa'
    manhua = 'manhua'


class PeopleSearchQueryOrderby(StrEnum):
    mal_id = 'mal_id'
    name = 'name'
    birthday = 'birthday'
    favorites = 'favorites'


class ProducersQueryOrderby(StrEnum):
    mal_id = 'mal_id'
    count_ = 'count'
    favorites = 'favorites'
    established = 'established'


class SearchQuerySort(StrEnum):
    desc = 'desc'
    asc = 'asc'


class TopAnimeFilter(StrEnum):
    airing = 'airing'
    upcoming = 'upcoming'
    bypopularity = 'bypopularity'
    favorite = 'favorite'


class TopMangaFilter(StrEnum):
    publishing = 'publishing'
    upcoming = 'upcoming'
    bypopularity = 'bypopularity'
    favorite = 'favorite'


class TopReviewsTypeEnum(StrEnum):
    anime = 'anime'
    manga = 'manga'


class Datum(BaseModel):
    mal_id: int | None = Field(None, description='MyAnimeList ID')
    url: str | None = Field(
        None,
        description="MyAnimeList URL. This is the URL of the episode's video. If there is no video url, this will be null.",
    )
    title: str | None = Field(None, description='Title')
    title_japanese: str | None = Field(None, description='Title Japanese')
    title_romanji: str | None = Field(None, description='title_romanji')
    aired: str | None = Field(None, description='Aired Date ISO8601')
    score: Any | None = Field(
        None,
        description='Aggregated episode score (1.00 - 5.00) based on MyAnimeList user voting',
    )
    filler: bool | None = Field(None, description='Filler episode')
    recap: bool | None = Field(None, description='Recap episode')
    forum_url: str | None = Field(None, description='Episode discussion forum URL')


class Datum2(BaseModel):
    image_url: str | None = Field(None, description='Default JPG Image Size URL')
    large_image_url: str | None = Field(None, description='Large JPG Image Size URL')


class CharacterPictures(BaseModel):
    data: list[Datum2] | None = None


class Datum5(BaseModel):
    year: int | None = Field(None, description='Year')
    seasons: list[str] | None = Field(None, description='List of available seasons')


class Seasons(BaseModel):
    data: list[Datum5] | None = None


class Datum7(BaseModel):
    mal_id: int | None = Field(None, description='MyAnimeList ID')
    name: str | None = Field(None, description='Club Name')
    url: str | None = Field(None, description='Club URL')


class Episode(BaseModel):
    mal_id: str | None = Field(None, description='MyAnimeList ID')
    url: str | None = Field(None, description='MyAnimeList URL')
    title: str | None = Field(None, description='Episode Title')
    premium: bool | None = Field(None, description='For MyAnimeList Premium Users')


class AnimeEpisode(BaseModel):
    mal_id: int | None = Field(None, description='MyAnimeList ID')
    url: str | None = Field(None, description='MyAnimeList URL')
    title: str | None = Field(None, description='Title')
    title_japanese: str | None = Field(None, description='Title Japanese')
    title_romanji: str | None = Field(None, description='title_romanji')
    duration: int | None = Field(None, description='Episode duration in seconds')
    aired: str | None = Field(None, description='Aired Date ISO8601')
    filler: bool | None = Field(None, description='Filler episode')
    recap: bool | None = Field(None, description='Recap episode')
    synopsis: str | None = Field(None, description='Episode Synopsis')


class Type(StrEnum):
    TV = 'TV'
    OVA = 'OVA'
    Movie = 'Movie'
    Special = 'Special'
    ONA = 'ONA'
    Music = 'Music'
    TV_Special = 'TV Special'


class Status(StrEnum):
    Finished_Airing = 'Finished Airing'
    Currently_Airing = 'Currently Airing'
    Not_yet_aired = 'Not yet aired'


class Rating(StrEnum):
    G___All_Ages = 'G - All Ages'
    PG___Children = 'PG - Children'
    PG_13___Teens_13_or_older = 'PG-13 - Teens 13 or older'
    R___17___violence___profanity_ = 'R - 17+ (violence & profanity)'
    R____Mild_Nudity = 'R+ - Mild Nudity'
    Rx___Hentai = 'Rx - Hentai'


class Season(StrEnum):
    summer = 'summer'
    winter = 'winter'
    spring = 'spring'
    fall = 'fall'


class Theme(BaseModel):
    openings: list[str] | None = None
    endings: list[str] | None = None


class ExternalItem(BaseModel):
    name: str | None = None
    url: str | None = None


class StreamingItem(BaseModel):
    name: str | None = None
    url: str | None = None


class Score(BaseModel):
    score: int | None = Field(None, description='Scoring value')
    votes: int | None = Field(None, description='Number of votes for this score')
    percentage: float | None = Field(
        None, description='Percentage of votes for this score'
    )


class Data(BaseModel):
    watching: int | None = Field(
        None, description='Number of users watching the resource'
    )
    completed: int | None = Field(
        None, description='Number of users who have completed the resource'
    )
    on_hold: int | None = Field(
        None, description='Number of users who have put the resource on hold'
    )
    dropped: int | None = Field(
        None, description='Number of users who have dropped the resource'
    )
    plan_to_watch: int | None = Field(
        None, description='Number of users who have planned to watch the resource'
    )
    total: int | None = Field(
        None,
        description='Total number of users who have the resource added to their lists',
    )
    scores: list[Score] | None = None


class AnimeStatistics(BaseModel):
    data: Data | None = None


class Data1(BaseModel):
    openings: list[str] | None = None
    endings: list[str] | None = None


class AnimeThemes(BaseModel):
    data: Data1 | None = None


class Meta(BaseModel):
    title: str | None = None
    author: str | None = None


class Category(StrEnum):
    actors___artists = 'actors & artists'
    anime = 'anime'
    characters = 'characters'
    cities___neighborhoods = 'cities & neighborhoods'
    companies = 'companies'
    conventions = 'conventions'
    games = 'games'
    japan = 'japan'
    manga = 'manga'
    music = 'music'
    others = 'others'
    schools = 'schools'


class Access(StrEnum):
    public = 'public'
    private = 'private'
    secret = 'secret'


class Datum16(BaseModel):
    url: str | None = Field(None, description='User URL')
    username: str | None = Field(None, description="User's username")


class ClubStaff(BaseModel):
    data: list[Datum16] | None = None


class TrailerBase(BaseModel):
    youtube_id: str | None = Field(None, description='YouTube ID')
    url: str | None = Field(None, description='YouTube URL')
    embed_url: str | None = Field(None, description='Parsed Embed URL')


class Images(BaseModel):
    image_url: str | None = Field(None, description='Default Image Size URL (120x90)')
    small_image_url: str | None = Field(
        None, description='Small Image Size URL (640x480)'
    )
    medium_image_url: str | None = Field(
        None, description='Medium Image Size URL (320x180)'
    )
    large_image_url: str | None = Field(
        None, description='Large Image Size URL (480x360)'
    )
    maximum_image_url: str | None = Field(
        None, description='Maximum Image Size URL (1280x720)'
    )


class TrailerImages(BaseModel):
    images: Images | None = None


class From(BaseModel):
    day: int | None = Field(None, description='Day')
    month: int | None = Field(None, description='Month')
    year: int | None = Field(None, description='Year')


class To(BaseModel):
    day: int | None = Field(None, description='Day')
    month: int | None = Field(None, description='Month')
    year: int | None = Field(None, description='Year')


class Prop(BaseModel):
    from_: From | None = Field(None, alias='from', description='Date Prop From')
    to: To | None = Field(None, description='Date Prop To')
    string: str | None = Field(None, description='Raw parsed string')


class Daterange(BaseModel):
    from_: str | None = Field(None, alias='from', description='Date ISO8601')
    to: str | None = Field(None, description='Date ISO8601')
    prop: Prop | None = Field(None, description='Date Prop')


class Broadcast(BaseModel):
    day: str | None = Field(None, description='Day of the week')
    time: str | None = Field(None, description='Time in 24 hour format')
    timezone: str | None = Field(
        None,
        description='Timezone (Tz Database format https://en.wikipedia.org/wiki/List_of_tz_database_time_zones)',
    )
    string: str | None = Field(None, description='Raw parsed broadcast string')


class MalUrl(BaseModel):
    mal_id: int | None = Field(None, description='MyAnimeList ID')
    type: str | None = Field(None, description='Type of resource')
    name: str | None = Field(None, description='Resource Name/Title')
    url: str | None = Field(None, description='MyAnimeList URL')


class MalUrl2(BaseModel):
    mal_id: int | None = Field(None, description='MyAnimeList ID')
    type: str | None = Field(None, description='Type of resource')
    title: str | None = Field(None, description='Resource Name/Title')
    url: str | None = Field(None, description='MyAnimeList URL')


class EntryMeta(BaseModel):
    mal_id: int | None = Field(None, description='MyAnimeList ID')
    url: str | None = Field(None, description='MyAnimeList URL')
    image_url: str | None = Field(None, description='Image URL')
    name: str | None = Field(None, description='Entry Name/Title')


class Relation(BaseModel):
    relation: str | None = Field(None, description='Relation type')
    entry: list[MalUrl] | None = Field(None, description='Related entries')


class Pagination1(BaseModel):
    last_visible_page: int | None = None
    has_next_page: bool | None = None


class Pagination(BaseModel):
    pagination: Pagination1 | None = None


class Items(BaseModel):
    count: int | None = None
    total: int | None = None
    per_page: int | None = None


class Pagination2(BaseModel):
    last_visible_page: int | None = None
    has_next_page: bool | None = None
    current_page: int | None = None
    items: Items | None = None


class PaginationPlus(BaseModel):
    pagination: Pagination2 | None = None


class UserById(BaseModel):
    url: str | None = Field(None, description='MyAnimeList URL')
    username: str | None = Field(None, description='MyAnimeList Username')


class Jpg(BaseModel):
    image_url: str | None = Field(None, description='Image URL JPG')


class Webp(BaseModel):
    image_url: str | None = Field(None, description='Image URL WEBP')


class UserImages(BaseModel):
    jpg: Jpg | None = Field(None, description='Available images in JPG')
    webp: Webp | None = Field(None, description='Available images in WEBP')


class Jpg1(BaseModel):
    image_url: str | None = Field(None, description='Image URL JPG')
    small_image_url: str | None = Field(None, description='Small Image URL JPG')
    large_image_url: str | None = Field(None, description='Image URL JPG')


class Webp1(BaseModel):
    image_url: str | None = Field(None, description='Image URL WEBP')
    small_image_url: str | None = Field(None, description='Small Image URL WEBP')
    large_image_url: str | None = Field(None, description='Image URL WEBP')


class AnimeImages(BaseModel):
    jpg: Jpg1 | None = Field(None, description='Available images in JPG')
    webp: Webp1 | None = Field(None, description='Available images in WEBP')


class MangaImages(BaseModel):
    jpg: Jpg1 | None = Field(None, description='Available images in JPG')
    webp: Webp1 | None = Field(None, description='Available images in WEBP')


class Jpg3(BaseModel):
    image_url: str | None = Field(None, description='Image URL JPG')
    small_image_url: str | None = Field(None, description='Small Image URL JPG')


class Webp3(BaseModel):
    image_url: str | None = Field(None, description='Image URL WEBP')
    small_image_url: str | None = Field(None, description='Small Image URL WEBP')


class CharacterImages(BaseModel):
    jpg: Jpg3 | None = Field(None, description='Available images in JPG')
    webp: Webp3 | None = Field(None, description='Available images in WEBP')


class Jpg4(BaseModel):
    image_url: str | None = Field(None, description='Image URL JPG')


class PeopleImages(BaseModel):
    jpg: Jpg4 | None = Field(None, description='Available images in JPG')


class CommonImages(BaseModel):
    jpg: Jpg4 | None = Field(None, description='Available images in JPG')


class Title(BaseModel):
    type: str | None = Field(None, description='Title type')
    title: str | None = Field(None, description='Title value')


class Datum17(BaseModel):
    name: str | None = None
    url: str | None = None


class ExternalLinks(BaseModel):
    data: list[Datum17] | None = None


class LastComment(BaseModel):
    url: str | None = Field(None, description='Last comment URL')
    author_username: str | None = Field(None, description='Author MyAnimeList Username')
    author_url: str | None = Field(None, description='Author Profile URL')
    date: str | None = Field(None, description='Last comment date posted ISO8601')


class Datum18(BaseModel):
    mal_id: int | None = Field(None, description='MyAnimeList ID')
    url: str | None = Field(None, description='MyAnimeList URL')
    title: str | None = Field(None, description='Title')
    date: str | None = Field(None, description='Post Date ISO8601')
    author_username: str | None = Field(None, description='Author MyAnimeList Username')
    author_url: str | None = Field(None, description='Author Profile URL')
    comments: int | None = Field(None, description='Comment count')
    last_comment: LastComment | None = Field(None, description='Last comment details')


class Forum(BaseModel):
    data: list[Datum18] | None = None


class Genre(BaseModel):
    mal_id: int | None = Field(None, description='MyAnimeList ID')
    name: str | None = Field(None, description='Genre Name')
    url: str | None = Field(None, description='MyAnimeList URL')
    count: int | None = Field(None, description="Genre's entry count")


class Magazine(BaseModel):
    mal_id: int | None = Field(None, description='MyAnimeList ID')
    name: str | None = Field(None, description='Magazine Name')
    url: str | None = Field(None, description='MyAnimeList URL')
    count: int | None = Field(None, description="Magazine's manga count")


class Type2(StrEnum):
    Manga = 'Manga'
    Novel = 'Novel'
    Light_Novel = 'Light Novel'
    One_shot = 'One-shot'
    Doujinshi = 'Doujinshi'
    Manhua = 'Manhua'
    Manhwa = 'Manhwa'
    OEL = 'OEL'


class Status2(StrEnum):
    Finished = 'Finished'
    Publishing = 'Publishing'
    On_Hiatus = 'On Hiatus'
    Discontinued = 'Discontinued'
    Not_yet_published = 'Not yet published'


class Relation2(BaseModel):
    relation: str | None = Field(None, description='Relation type')
    entry: list[MalUrl] | None = None


class MangaFull(BaseModel):
    mal_id: int | None = Field(None, description='MyAnimeList ID')
    url: str | None = Field(None, description='MyAnimeList URL')
    images: MangaImages | None = None
    approved: bool | None = Field(
        None, description='Whether the entry is pending approval on MAL or not'
    )
    titles: list[Title] | None = Field(None, description='All Titles')
    title: str | None = Field(None, deprecated=True, description='Title')
    title_english: str | None = Field(
        None, deprecated=True, description='English Title'
    )
    title_japanese: str | None = Field(
        None, deprecated=True, description='Japanese Title'
    )
    title_synonyms: list[str] | None = Field(
        None, deprecated=True, description='Other Titles'
    )
    type: Type2 | None = Field(None, description='Manga Type')
    chapters: int | None = Field(None, description='Chapter count')
    volumes: int | None = Field(None, description='Volume count')
    status: Status2 | None = Field(None, description='Publishing status')
    publishing: bool | None = Field(None, description='Publishing boolean')
    published: Daterange | None = None
    score: float | None = Field(None, description='Score')
    scored_by: int | None = Field(None, description='Number of users')
    rank: int | None = Field(None, description='Ranking')
    popularity: int | None = Field(None, description='Popularity')
    members: int | None = Field(
        None, description='Number of users who have added this entry to their list'
    )
    favorites: int | None = Field(
        None, description='Number of users who have favorited this entry'
    )
    synopsis: str | None = Field(None, description='Synopsis')
    background: str | None = Field(None, description='Background')
    authors: list[MalUrl] | None = None
    serializations: list[MalUrl] | None = None
    genres: list[MalUrl] | None = None
    explicit_genres: list[MalUrl] | None = None
    themes: list[MalUrl] | None = None
    demographics: list[MalUrl] | None = None
    relations: list[Relation2] | None = None
    external: list[ExternalItem] | None = None


class Manga(BaseModel):
    mal_id: int | None = Field(None, description='MyAnimeList ID')
    url: str | None = Field(None, description='MyAnimeList URL')
    images: MangaImages | None = None
    approved: bool | None = Field(
        None, description='Whether the entry is pending approval on MAL or not'
    )
    titles: list[Title] | None = Field(None, description='All Titles')
    title: str | None = Field(None, deprecated=True, description='Title')
    title_english: str | None = Field(
        None, deprecated=True, description='English Title'
    )
    title_japanese: str | None = Field(
        None, deprecated=True, description='Japanese Title'
    )
    type: Type2 | None = Field(None, description='Manga Type')
    chapters: int | None = Field(None, description='Chapter count')
    volumes: int | None = Field(None, description='Volume count')
    status: Status2 | None = Field(None, description='Publishing status')
    publishing: bool | None = Field(None, description='Publishing boolean')
    published: Daterange | None = None
    score: float | None = Field(None, description='Score')
    scored_by: int | None = Field(None, description='Number of users')
    rank: int | None = Field(None, description='Ranking')
    popularity: int | None = Field(None, description='Popularity')
    members: int | None = Field(
        None, description='Number of users who have added this entry to their list'
    )
    favorites: int | None = Field(
        None, description='Number of users who have favorited this entry'
    )
    synopsis: str | None = Field(None, description='Synopsis')
    background: str | None = Field(None, description='Background')
    authors: list[MalUrl] | None = None
    serializations: list[MalUrl] | None = None
    genres: list[MalUrl] | None = None
    explicit_genres: list[MalUrl] | None = None
    themes: list[MalUrl] | None = None
    demographics: list[MalUrl] | None = None


class Data4(BaseModel):
    reading: int | None = Field(
        None, description='Number of users reading the resource'
    )
    completed: int | None = Field(
        None, description='Number of users who have completed the resource'
    )
    on_hold: int | None = Field(
        None, description='Number of users who have put the resource on hold'
    )
    dropped: int | None = Field(
        None, description='Number of users who have dropped the resource'
    )
    plan_to_read: int | None = Field(
        None, description='Number of users who have planned to read the resource'
    )
    total: int | None = Field(
        None,
        description='Total number of users who have the resource added to their lists',
    )
    scores: list[Score] | None = None


class MangaStatistics(BaseModel):
    data: Data4 | None = None


class Data5(BaseModel):
    moreinfo: str | None = Field(
        None, description='Additional information on the entry'
    )


class Moreinfo(BaseModel):
    data: Data5 | None = None


class Datum20(BaseModel):
    mal_id: int | None = Field(None, description='MyAnimeList ID')
    url: str | None = Field(None, description='MyAnimeList URL')
    title: str | None = Field(None, description='Title')
    date: str | None = Field(None, description='Post Date ISO8601')
    author_username: str | None = Field(None, description='Author MyAnimeList Username')
    author_url: str | None = Field(None, description='Author Profile URL')
    forum_url: str | None = Field(None, description='Forum topic URL')
    images: CommonImages | None = None
    comments: int | None = Field(None, description='Comment count')
    excerpt: str | None = Field(None, description='Excerpt')


class News(BaseModel):
    data: list[Datum20] | None = None


class Person(BaseModel):
    mal_id: int | None = Field(None, description='MyAnimeList ID')
    url: str | None = Field(None, description='MyAnimeList URL')
    website_url: str | None = Field(None, description="Person's website URL")
    images: PeopleImages | None = None
    name: str | None = Field(None, description='Name')
    given_name: str | None = Field(None, description='Given Name')
    family_name: str | None = Field(None, description='Family Name')
    alternate_names: list[str] | None = Field(None, description='Other Names')
    birthday: str | None = Field(None, description='Birthday Date ISO8601')
    favorites: int | None = Field(
        None, description='Number of users who have favorited this entry'
    )
    about: str | None = Field(None, description='Biography')


class Datum24(BaseModel):
    images: AnimeImages | None = None


class Pictures(BaseModel):
    data: list[Datum24] | None = None


class Datum25(BaseModel):
    images: CommonImages | None = None


class PicturesVariants(BaseModel):
    data: list[Datum25] | None = None


class ProducerFull(BaseModel):
    mal_id: int | None = Field(None, description='MyAnimeList ID')
    url: str | None = Field(None, description='MyAnimeList URL')
    titles: list[Title] | None = Field(None, description='All titles')
    images: CommonImages | None = None
    favorites: int | None = Field(
        None, description="Producers's member favorites count"
    )
    count: int | None = Field(None, description="Producers's anime count")
    established: str | None = Field(None, description='Established Date ISO8601')
    about: str | None = Field(None, description='About the Producer')
    external: list[ExternalItem] | None = None


class Producer(BaseModel):
    mal_id: int | None = Field(None, description='MyAnimeList ID')
    url: str | None = Field(None, description='MyAnimeList URL')
    titles: list[Title] | None = Field(None, description='All titles')
    images: CommonImages | None = None
    favorites: int | None = Field(
        None, description="Producers's member favorites count"
    )
    count: int | None = Field(None, description="Producers's anime count")
    established: str | None = Field(None, description='Established Date ISO8601')
    about: str | None = Field(None, description='About the Producer')


class Datum26(BaseModel):
    about: str | None = Field(
        None,
        description='User About. NOTE: About information is customizable by users through BBCode on MyAnimeList. This means users can add multimedia content, different text sizes, etc. Due to this freeform, Jikan returns parsed HTML. Validate on your end!',
    )


class UserAbout(BaseModel):
    data: list[Datum26] | None = None


class Anime1(BaseModel):
    days_watched: float | None = Field(
        None, description='Number of days spent watching Anime'
    )
    mean_score: float | None = Field(None, description='Mean Score')
    watching: int | None = Field(None, description='Anime Watching')
    completed: int | None = Field(None, description='Anime Completed')
    on_hold: int | None = Field(None, description='Anime On-Hold')
    dropped: int | None = Field(None, description='Anime Dropped')
    plan_to_watch: int | None = Field(None, description='Anime Planned to Watch')
    total_entries: int | None = Field(
        None, description='Total Anime entries on User list'
    )
    rewatched: int | None = Field(None, description='Anime re-watched')
    episodes_watched: int | None = Field(
        None, description='Number of Anime Episodes Watched'
    )


class Manga1(BaseModel):
    days_read: float | None = Field(
        None, description='Number of days spent reading Manga'
    )
    mean_score: float | None = Field(None, description='Mean Score')
    reading: int | None = Field(None, description='Manga Reading')
    completed: int | None = Field(None, description='Manga Completed')
    on_hold: int | None = Field(None, description='Manga On-Hold')
    dropped: int | None = Field(None, description='Manga Dropped')
    plan_to_read: int | None = Field(None, description='Manga Planned to Read')
    total_entries: int | None = Field(
        None, description='Total Manga entries on User list'
    )
    reread: int | None = Field(None, description='Manga re-read')
    chapters_read: int | None = Field(None, description='Number of Manga Chapters Read')
    volumes_read: int | None = Field(None, description='Number of Manga Volumes Read')


class Statistics(BaseModel):
    anime: Anime1 | None = Field(None, description='Anime Statistics')
    manga: Manga1 | None = Field(None, description='Manga Statistics')


class UserProfileFull(BaseModel):
    mal_id: int | None = Field(None, description='MyAnimeList ID')
    username: str | None = Field(None, description='MyAnimeList Username')
    url: str | None = Field(None, description='MyAnimeList URL')
    images: UserImages | None = None
    last_online: str | None = Field(None, description='Last Online Date ISO8601')
    gender: str | None = Field(None, description='User Gender')
    birthday: str | None = Field(None, description='Birthday Date ISO8601')
    location: str | None = Field(None, description='Location')
    joined: str | None = Field(None, description='Joined Date ISO8601')
    statistics: Statistics | None = None
    external: list[ExternalItem] | None = None


class History(BaseModel):
    entry: MalUrl | None = None
    increment: int | None = Field(
        None, description='Number of episodes/chapters watched/read'
    )
    date: str | None = Field(None, description='Date ISO8601')


class UserProfile(BaseModel):
    mal_id: int | None = Field(None, description='MyAnimeList ID')
    username: str | None = Field(None, description='MyAnimeList Username')
    url: str | None = Field(None, description='MyAnimeList URL')
    images: UserImages | None = None
    last_online: str | None = Field(None, description='Last Online Date ISO8601')
    gender: str | None = Field(None, description='User Gender')
    birthday: str | None = Field(None, description='Birthday Date ISO8601')
    location: str | None = Field(None, description='Location')
    joined: str | None = Field(None, description='Joined Date ISO8601')


class Jpg6(BaseModel):
    image_url: str | None = Field(None, description='Image URL JPG (225x335)')


class Webp4(BaseModel):
    image_url: str | None = Field(None, description='Image URL WEBP (225x335)')


class Images1(BaseModel):
    jpg: Jpg6 | None = Field(None, description='Available images in JPG')
    webp: Webp4 | None = Field(None, description='Available images in WEBP')


class AnimeStats(BaseModel):
    days_watched: float | None = Field(
        None, description='Number of days spent watching Anime'
    )
    mean_score: float | None = Field(None, description='Mean Score')
    watching: int | None = Field(None, description='Anime Watching')
    completed: int | None = Field(None, description='Anime Completed')
    on_hold: int | None = Field(None, description='Anime On-Hold')
    dropped: int | None = Field(None, description='Anime Dropped')
    plan_to_watch: int | None = Field(None, description='Anime Planned to Watch')
    total_entries: int | None = Field(
        None, description='Total Anime entries on User list'
    )
    rewatched: int | None = Field(None, description='Anime re-watched')
    episodes_watched: int | None = Field(
        None, description='Number of Anime Episodes Watched'
    )


class MangaStats(BaseModel):
    days_read: float | None = Field(
        None, description='Number of days spent reading Manga'
    )
    mean_score: float | None = Field(None, description='Mean Score')
    reading: int | None = Field(None, description='Manga Reading')
    completed: int | None = Field(None, description='Manga Completed')
    on_hold: int | None = Field(None, description='Manga On-Hold')
    dropped: int | None = Field(None, description='Manga Dropped')
    plan_to_read: int | None = Field(None, description='Manga Planned to Read')
    total_entries: int | None = Field(
        None, description='Total Manga entries on User list'
    )
    reread: int | None = Field(None, description='Manga re-read')
    chapters_read: int | None = Field(None, description='Number of Manga Chapters Read')
    volumes_read: int | None = Field(None, description='Number of Manga Volumes Read')


class Favorites(BaseModel):
    anime: list[EntryMeta] | None = Field(None, description='Favorite Anime')
    manga: list[EntryMeta] | None = Field(None, description='Favorite Manga')
    characters: list[EntryMeta] | None = Field(None, description='Favorite Characters')
    people: list[EntryMeta] | None = Field(None, description='Favorite People')


class Datum27(BaseModel):
    mal_id: int | None = Field(None, description='MyAnimeList ID')
    username: str | None = Field(None, description='MyAnimeList Username')
    url: str | None = Field(None, description='MyAnimeList URL')
    images: Images1 | None = Field(None, description='Images')
    last_online: str | None = Field(None, description='Last Online Date ISO8601')
    gender: str | None = Field(None, description='User Gender')
    birthday: str | None = Field(None, description='Birthday Date ISO8601')
    location: str | None = Field(None, description='Location')
    joined: str | None = Field(None, description='Joined Date ISO8601')
    anime_stats: AnimeStats | None = Field(None, description='Anime Stats')
    manga_stats: MangaStats | None = Field(None, description='Manga Stats')
    favorites: Favorites | None = Field(None, description='Favorite entries')
    about: str | None = Field(
        None,
        description='User About. NOTE: About information is customizable by users through BBCode on MyAnimeList. This means users can add multimedia content, different text sizes, etc. Due to this freeform, Jikan returns parsed HTML. Validate on your end!',
    )


class UsersTemp(BaseModel):
    data: list[Datum27] | None = None


class Data7(BaseModel):
    anime: Anime1 | None = Field(None, description='Anime Statistics')
    manga: Manga1 | None = Field(None, description='Manga Statistics')


class UserStatistics(BaseModel):
    data: Data7 | None = None


class Data8(BaseModel):
    url: str | None = Field(None, description='Recommendation MyAnimeList URL')
    votes: int | None = Field(
        None, description='Number of users who have recommended this entry'
    )


class Reactions(BaseModel):
    overall: int | None = Field(None, description='Overall reaction count')
    nice: int | None = Field(None, description='Nice reaction count')
    love_it: int | None = Field(None, description='Love it reaction count')
    funny: int | None = Field(None, description='Funny reaction count')
    confusing: int | None = Field(None, description='Confusing reaction count')
    informative: int | None = Field(None, description='Informative reaction count')
    well_written: int | None = Field(None, description='Well written reaction count')
    creative: int | None = Field(None, description='Creative reaction count')


class MangaReview(BaseModel):
    mal_id: int | None = Field(None, description='MyAnimeList ID')
    url: str | None = Field(None, description='MyAnimeList review URL')
    type: str | None = Field(None, description='Entry type')
    reactions: Reactions | None = Field(
        None, description='User reaction count on the review'
    )
    date: str | None = Field(None, description='Review created date ISO8601')
    review: str | None = Field(None, description='Review content')
    score: int | None = Field(None, description='Number of user votes on the Review')
    tags: list[str] | None = Field(None, description='Review tags')
    is_spoiler: bool | None = Field(None, description='The review contains spoiler')
    is_preliminary: bool | None = Field(
        None, description='The review was made before the entry was completed'
    )


class AnimeReview(BaseModel):
    mal_id: int | None = Field(None, description='MyAnimeList ID')
    url: str | None = Field(None, description='MyAnimeList review URL')
    type: str | None = Field(None, description='Entry type')
    reactions: Reactions | None = Field(
        None, description='User reaction count on the review'
    )
    date: str | None = Field(None, description='Review created date ISO8601')
    review: str | None = Field(None, description='Review content')
    score: int | None = Field(None, description='Number of user votes on the Review')
    tags: list[str] | None = Field(None, description='Review tags')
    is_spoiler: bool | None = Field(None, description='The review contains spoiler')
    is_preliminary: bool | None = Field(
        None, description='The review was made before the entry was completed'
    )
    episodes_watched: int | None = Field(None, description='Number of episodes watched')


class Datum32(BaseModel):
    name: str | None = None
    url: str | None = None


class StreamingLinks(BaseModel):
    data: list[Datum32] | None = None


class AnimeEpisodes(Pagination):
    data: list[Datum] | None = None


class AnimeNews(Pagination, News):
    pass


class Datum1(BaseModel):
    mal_id: int | None = Field(None, description='MyAnimeList ID or Episode Number')
    title: str | None = Field(None, description='Episode Title')
    episode: str | None = Field(None, description='Episode Subtitle')
    url: str | None = Field(None, description='Episode Page URL')
    images: CommonImages | None = None


class AnimeVideosEpisodes(Pagination):
    data: list[Datum1] | None = None


class Datum3(BaseModel):
    username: str | None = Field(None, description="User's username")
    url: str | None = Field(None, description='User URL')
    images: UserImages | None = None


class ClubMember(BaseModel):
    data: list[Datum3] | None = None


class MangaNews(Pagination, News):
    pass


class MangaPictures(BaseModel):
    data: list[MangaImages] | None = None


class PersonPictures(BaseModel):
    data: list[PeopleImages] | None = None


class Datum4(BaseModel):
    url: str | None = Field(None, description='MyAnimeList URL')
    username: str | None = Field(None, description='MyAnimeList Username')
    images: UserImages | None = None
    last_online: str | None = Field(None, description='Last Online Date ISO8601')


class UsersSearch(Pagination):
    data: list[Datum4] | None = None


class ReviewsCollection(BaseModel):
    data: list[AnimeReview | MangaReview] | None = None


class UserClubs(Pagination):
    data: list[Datum7] | None = None


class Character1(BaseModel):
    mal_id: int | None = Field(None, description='MyAnimeList ID')
    url: str | None = Field(None, description='MyAnimeList URL')
    images: CharacterImages | None = None
    name: str | None = Field(None, description='Character Name')


class Person1(BaseModel):
    mal_id: int | None = None
    url: str | None = None
    images: PeopleImages | None = None
    name: str | None = None


class VoiceActor(BaseModel):
    person: Person1 | None = None
    language: str | None = None


class Datum10(BaseModel):
    character: Character1 | None = Field(None, description='Character details')
    role: str | None = Field(None, description="Character's Role")
    voice_actors: list[VoiceActor] | None = None


class AnimeCharacters(BaseModel):
    data: list[Datum10] | None = None


class AnimeFull(BaseModel):
    mal_id: int | None = Field(None, description='MyAnimeList ID')
    url: str | None = Field(None, description='MyAnimeList URL')
    images: AnimeImages | None = None
    trailer: TrailerBase | None = None
    approved: bool | None = Field(
        None, description='Whether the entry is pending approval on MAL or not'
    )
    titles: list[Title] | None = Field(None, description='All titles')
    title: str | None = Field(None, deprecated=True, description='Title')
    title_english: str | None = Field(
        None, deprecated=True, description='English Title'
    )
    title_japanese: str | None = Field(
        None, deprecated=True, description='Japanese Title'
    )
    title_synonyms: list[str] | None = Field(
        None, deprecated=True, description='Other Titles'
    )
    type: Type | None = Field(None, description='Anime Type')
    source: str | None = Field(
        None, description='Original Material/Source adapted from'
    )
    episodes: int | None = Field(None, description='Episode count')
    status: Status | None = Field(None, description='Airing status')
    airing: bool | None = Field(None, description='Airing boolean')
    aired: Daterange | None = None
    duration: str | None = Field(None, description='Parsed raw duration')
    rating: Rating | None = Field(None, description='Anime audience rating')
    score: float | None = Field(None, description='Score')
    scored_by: int | None = Field(None, description='Number of users')
    rank: int | None = Field(None, description='Ranking')
    popularity: int | None = Field(None, description='Popularity')
    members: int | None = Field(
        None, description='Number of users who have added this entry to their list'
    )
    favorites: int | None = Field(
        None, description='Number of users who have favorited this entry'
    )
    synopsis: str | None = Field(None, description='Synopsis')
    background: str | None = Field(None, description='Background')
    season: Season | None = Field(None, description='Season')
    year: int | None = Field(None, description='Year')
    broadcast: Broadcast | None = None
    producers: list[MalUrl] | None = None
    licensors: list[MalUrl] | None = None
    studios: list[MalUrl] | None = None
    genres: list[MalUrl] | None = None
    explicit_genres: list[MalUrl] | None = None
    themes: list[MalUrl] | None = None
    demographics: list[MalUrl] | None = None
    relations: list[Relation2] | None = None
    theme: Theme | None = None
    external: list[ExternalItem] | None = None
    streaming: list[StreamingItem] | None = None


class Datum11(BaseModel):
    relation: str | None = Field(None, description='Relation type')
    entry: list[MalUrl] | None = None


class AnimeRelations(BaseModel):
    data: list[Datum11] | None = None


class Anime(BaseModel):
    mal_id: int | None = Field(None, description='MyAnimeList ID')
    url: str | None = Field(None, description='MyAnimeList URL')
    images: AnimeImages | None = None
    trailer: TrailerBase | None = None
    approved: bool | None = Field(
        None, description='Whether the entry is pending approval on MAL or not'
    )
    titles: list[Title] | None = Field(None, description='All titles')
    title: str | None = Field(None, deprecated=True, description='Title')
    title_english: str | None = Field(
        None, deprecated=True, description='English Title'
    )
    title_japanese: str | None = Field(
        None, deprecated=True, description='Japanese Title'
    )
    title_synonyms: list[str] | None = Field(
        None, deprecated=True, description='Other Titles'
    )
    type: Type | None = Field(None, description='Anime Type')
    source: str | None = Field(
        None, description='Original Material/Source adapted from'
    )
    episodes: int | None = Field(None, description='Episode count')
    status: Status | None = Field(None, description='Airing status')
    airing: bool | None = Field(None, description='Airing boolean')
    aired: Daterange | None = None
    duration: str | None = Field(None, description='Parsed raw duration')
    rating: Rating | None = Field(None, description='Anime audience rating')
    score: float | None = Field(None, description='Score')
    scored_by: int | None = Field(None, description='Number of users')
    rank: int | None = Field(None, description='Ranking')
    popularity: int | None = Field(None, description='Popularity')
    members: int | None = Field(
        None, description='Number of users who have added this entry to their list'
    )
    favorites: int | None = Field(
        None, description='Number of users who have favorited this entry'
    )
    synopsis: str | None = Field(None, description='Synopsis')
    background: str | None = Field(None, description='Background')
    season: Season | None = Field(None, description='Season')
    year: int | None = Field(None, description='Year')
    broadcast: Broadcast | None = None
    producers: list[MalUrl] | None = None
    licensors: list[MalUrl] | None = None
    studios: list[MalUrl] | None = None
    genres: list[MalUrl] | None = None
    explicit_genres: list[MalUrl] | None = None
    themes: list[MalUrl] | None = None
    demographics: list[MalUrl] | None = None


class Person2(BaseModel):
    mal_id: int | None = Field(None, description='MyAnimeList ID')
    url: str | None = Field(None, description='MyAnimeList URL')
    images: PeopleImages | None = None
    name: str | None = Field(None, description='Name')


class Datum12(BaseModel):
    person: Person2 | None = Field(None, description='Person details')
    positions: list[str] | None = Field(None, description='Staff Positions')


class AnimeStaff(BaseModel):
    data: list[Datum12] | None = None


class Episode1(BaseModel):
    mal_id: int | None = Field(None, description='MyAnimeList ID')
    url: str | None = Field(None, description='MyAnimeList URL')
    title: str | None = Field(None, description='Title')
    episode: str | None = Field(None, description='Episode')
    images: CommonImages | None = None


class Character(BaseModel):
    mal_id: int | None = Field(None, description='MyAnimeList ID')
    url: str | None = Field(None, description='MyAnimeList URL')
    images: CharacterImages | None = None
    name: str | None = Field(None, description='Name')
    name_kanji: str | None = Field(None, description='Name')
    nicknames: list[str] | None = Field(None, description='Other Names')
    favorites: int | None = Field(
        None, description='Number of users who have favorited this entry'
    )
    about: str | None = Field(None, description='Biography')


class Data3(BaseModel):
    anime: list[MalUrl] | None = None
    manga: list[MalUrl] | None = None
    characters: list[MalUrl] | None = None


class ClubRelations(BaseModel):
    data: Data3 | None = None


class Club(BaseModel):
    mal_id: int | None = Field(None, description='MyAnimeList ID')
    name: str | None = Field(None, description='Club name')
    url: str | None = Field(None, description='Club URL')
    images: CommonImages | None = None
    members: int | None = Field(None, description='Number of club members')
    category: Category | None = Field(None, description='Club Category')
    created: str | None = Field(None, description='Date Created ISO8601')
    access: Access | None = Field(None, description='Club access')


class Trailer(TrailerBase, TrailerImages):
    pass


class UserMeta(BaseModel):
    username: str | None = Field(None, description='MyAnimeList Username')
    url: str | None = Field(None, description='MyAnimeList Profile URL')
    images: UserImages | None = None


class AnimeMeta(BaseModel):
    mal_id: int | None = Field(None, description='MyAnimeList ID')
    url: str | None = Field(None, description='MyAnimeList URL')
    images: AnimeImages | None = None
    title: str | None = Field(None, description='Entry title')


class MangaMeta(BaseModel):
    mal_id: int | None = Field(None, description='MyAnimeList ID')
    url: str | None = Field(None, description='MyAnimeList URL')
    images: MangaImages | None = None
    title: str | None = Field(None, description='Entry title')


class CharacterMeta(BaseModel):
    mal_id: int | None = Field(None, description='MyAnimeList ID')
    url: str | None = Field(None, description='MyAnimeList URL')
    images: CharacterImages | None = None
    name: str | None = Field(None, description='Entry name')


class PersonMeta(BaseModel):
    mal_id: int | None = Field(None, description='MyAnimeList ID')
    url: str | None = Field(None, description='MyAnimeList URL')
    images: PeopleImages | None = None
    name: str | None = Field(None, description='Entry name')


class Genres(BaseModel):
    data: list[Genre] | None = None


class Magazines(Pagination):
    data: list[Magazine] | None = None


class Datum19(BaseModel):
    character: CharacterMeta | None = None
    role: str | None = Field(None, description="Character's Role")


class MangaCharacters(BaseModel):
    data: list[Datum19] | None = None


class MangaSearch(PaginationPlus):
    data: list[Manga] | None = None


class Datum21(BaseModel):
    position: str | None = Field(None, description="Person's position")
    anime: AnimeMeta | None = None


class PersonAnime(BaseModel):
    data: list[Datum21] | None = None


class PeopleSearch(PaginationPlus):
    data: list[Person] | None = None


class AnimeItem1(BaseModel):
    position: str | None = Field(None, description="Person's position")
    anime: AnimeMeta | None = None


class MangaItem1(BaseModel):
    position: str | None = Field(None, description="Person's position")
    manga: MangaMeta | None = None


class Voice1(BaseModel):
    role: str | None = Field(None, description="Person's Character's role in the anime")
    anime: AnimeMeta | None = None
    character: CharacterMeta | None = None


class PersonFull(BaseModel):
    mal_id: int | None = Field(None, description='MyAnimeList ID')
    url: str | None = Field(None, description='MyAnimeList URL')
    website_url: str | None = Field(None, description="Person's website URL")
    images: PeopleImages | None = None
    name: str | None = Field(None, description='Name')
    given_name: str | None = Field(None, description='Given Name')
    family_name: str | None = Field(None, description='Family Name')
    alternate_names: list[str] | None = Field(None, description='Other Names')
    birthday: str | None = Field(None, description='Birthday Date ISO8601')
    favorites: int | None = Field(
        None, description='Number of users who have favorited this entry'
    )
    about: str | None = Field(None, description='Biography')
    anime: list[AnimeItem1] | None = None
    manga: list[MangaItem1] | None = None
    voices: list[Voice1] | None = None


class Datum22(BaseModel):
    position: str | None = Field(None, description="Person's position")
    manga: MangaMeta | None = None


class PersonManga(BaseModel):
    data: list[Datum22] | None = None


class Datum23(BaseModel):
    role: str | None = Field(None, description="Person's Character's role in the anime")
    anime: AnimeMeta | None = None
    character: CharacterMeta | None = None


class PersonVoiceActingRoles(BaseModel):
    data: list[Datum23] | None = None


class Producers(Pagination):
    data: list[Producer] | None = None


class AnimeItem2(AnimeMeta):
    type: str | None = None
    start_year: int | None = None


class MangaItem2(MangaMeta):
    type: str | None = None
    start_year: int | None = None


class Character2(CharacterMeta, MalUrl2):
    pass


class UserFavorites(BaseModel):
    anime: list[AnimeItem2] | None = Field(None, description='Favorite Anime')
    manga: list[MangaItem2] | None = Field(None, description='Favorite Manga')
    characters: list[Character2] | None = Field(None, description='Favorite Characters')
    people: list[CharacterMeta] | None = Field(None, description='Favorite People')


class UserHistory(BaseModel):
    data: list[History] | None = None


class AnimeItem3(BaseModel):
    entry: AnimeMeta | None = None
    score: int | None = None
    status: str | None = None
    episodes_seen: int | None = None
    episodes_total: int | None = None
    date: str | None = Field(None, description='ISO8601 format')


class MangaItem3(BaseModel):
    entry: MangaMeta | None = None
    score: int | None = None
    status: str | None = None
    chapters_read: int | None = None
    chapters_total: int | None = None
    volumes_read: int | None = None
    volumes_total: int | None = None
    date: str | None = Field(None, description='ISO8601 format')


class Data6(BaseModel):
    anime: list[AnimeItem3] | None = Field(None, description='Last updated Anime')
    manga: list[MangaItem3] | None = Field(None, description='Last updated Manga')


class UserUpdates(BaseModel):
    data: Data6 | None = None


class Datum28(BaseModel):
    mal_id: str | None = Field(
        None,
        description="MAL IDs of recommendations is both of the MAL ID's with a `-` delimiter",
    )
    entry: list[AnimeMeta | MangaMeta] | None = Field(
        None, description='Array of 2 entries that are being recommended to each other'
    )
    content: str | None = Field(
        None, description='Recommendation context provided by the user'
    )
    user: UserById | None = None


class Recommendations(Pagination):
    data: list[Datum28] | None = None


class Datum29(BaseModel):
    entry: AnimeMeta | MangaMeta | None = None


class EntryRecommendations(BaseModel):
    data: list[Datum29] | Data8 | None = None


class Datum30(AnimeReview):
    user: UserMeta | None = None


class AnimeReviews(Pagination):
    data: list[Datum30] | None = None


class Datum31(MangaReview):
    user: UserMeta | None = None


class MangaReviews(Pagination):
    data: list[Datum31] | None = None


class Datum33(BaseModel):
    user: UserMeta | None = None
    score: int | None = Field(None, description='User Score')
    status: str | None = Field(None, description='User list status')
    episodes_seen: int | None = Field(None, description='Number of episodes seen')
    episodes_total: int | None = Field(None, description='Total number of episodes')
    date: str | None = Field(None, description='Last updated date ISO8601')


class AnimeUserupdates(Pagination):
    data: list[Datum33] | None = None


class Datum34(BaseModel):
    user: UserMeta | None = None
    score: int | None = Field(None, description='User Score')
    status: str | None = Field(None, description='User list status')
    volumes_read: int | None = Field(None, description='Number of volumes read')
    volumes_total: int | None = Field(None, description='Total number of volumes')
    chapters_read: int | None = Field(None, description='Number of chapters read')
    chapters_total: int | None = Field(None, description='Total number of chapters')
    date: str | None = Field(None, description='Last updated date ISO8601')


class MangaUserupdates(Pagination):
    data: list[Datum34] | None = None


class Random(BaseModel):
    data: list[Anime | Manga | Character | Person] | None = None


class Schedules(PaginationPlus):
    data: list[Anime] | None = None


class Datum6(BaseModel):
    user: UserMeta | None = None
    last_online: str | None = Field(None, description='Last Online Date ISO8601 format')
    friends_since: str | None = Field(
        None, description='Friends Since Date ISO8601 format'
    )


class UserFriends(Pagination):
    data: list[Datum6] | None = None


class Datum8(BaseModel):
    entry: AnimeMeta | None = None
    episodes: list[Episode] | None = Field(
        None, description='Recent Episodes (max 2 listed)'
    )
    region_locked: bool | None = Field(None, description='Region Locked Episode')


class WatchEpisodes(Pagination):
    data: list[Datum8] | None = None


class Datum9(BaseModel):
    title: str | None = Field(None, description='Promo Title')
    entry: AnimeMeta | None = None
    trailer: Trailer | None = None


class WatchPromos(Pagination):
    data: list[Datum9] | None = None


class AnimeSearch(PaginationPlus):
    data: list[Anime] | None = None


class PromoItem(BaseModel):
    title: str | None = Field(None, description='Title')
    trailer: Trailer | None = None


class MusicVideo(BaseModel):
    title: str | None = Field(None, description='Title')
    video: Trailer | None = None
    meta: Meta | None = None


class Data2(BaseModel):
    promo: list[PromoItem] | None = None
    episodes: list[Episode1] | None = None
    music_videos: list[MusicVideo] | None = None


class AnimeVideos(BaseModel):
    data: Data2 | None = None


class Datum13(BaseModel):
    role: str | None = Field(None, description="Character's Role")
    anime: AnimeMeta | None = None


class CharacterAnime(BaseModel):
    data: list[Datum13] | None = None


class CharactersSearch(PaginationPlus):
    data: list[Character] | None = None


class AnimeItem(BaseModel):
    role: str | None = Field(None, description="Character's Role")
    anime: AnimeMeta | None = None


class MangaItem(BaseModel):
    role: str | None = Field(None, description="Character's Role")
    manga: MangaMeta | None = None


class Voice(BaseModel):
    language: str | None = Field(None, description="Character's Role")
    person: PersonMeta | None = None


class CharacterFull(BaseModel):
    mal_id: int | None = Field(None, description='MyAnimeList ID')
    url: str | None = Field(None, description='MyAnimeList URL')
    images: CharacterImages | None = None
    name: str | None = Field(None, description='Name')
    name_kanji: str | None = Field(None, description='Name')
    nicknames: list[str] | None = Field(None, description='Other Names')
    favorites: int | None = Field(
        None, description='Number of users who have favorited this entry'
    )
    about: str | None = Field(None, description='Biography')
    anime: list[AnimeItem] | None = None
    manga: list[MangaItem] | None = None
    voices: list[Voice] | None = None


class Datum14(BaseModel):
    role: str | None = Field(None, description="Character's Role")
    manga: MangaMeta | None = None


class CharacterManga(BaseModel):
    data: list[Datum14] | None = None


class Datum15(BaseModel):
    language: str | None = Field(None, description="Character's Role")
    person: PersonMeta | None = None


class CharacterVoiceActors(BaseModel):
    data: list[Datum15] | None = None


class ClubsSearch(Pagination):
    data: list[Club] | None = None
